# Generated by Django 6.0 on 2026-01-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название ресторана"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="content/resto/", verbose_name="Изображение"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание ресторана")),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес ресторана"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон ресторана"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email ресторана"),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True,
                        help_text="Пн-Вс: 11:00-23:00",
                        null=True,
                        verbose_name="Рабочие часы",
                    ),
                ),
                (
                    "about_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="История ресторана"
                    ),
                ),
                (
                    "about_mission",
                    models.TextField(
                        blank=True, null=True, verbose_name="Миссия ресторана"
                    ),
                ),
                (
                    "team_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание команды"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о ресторане",
                "verbose_name_plural": "Информация о ресторане",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Подробности"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="content/team/", verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name": "Член команды",
                "verbose_name_plural": "Команда",
            },
        ),
    ]
