# Generated by Django 6.0 on 2026-01-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
            ],
            options={
                "verbose_name": "Сообщение обратной связи",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
