# Generated by Django 6.0 on 2026-01-05 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Минимум 120 минут (2 часа)",
                        validators=[django.core.validators.MinValueValidator(120)],
                        verbose_name="Длительность брони (мин)",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveSmallIntegerField(verbose_name="Количество гостей"),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Имя клиента"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер столика",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вместимость (чел.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для бронирования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["number"],
            },
        ),
    ]
