# Generated by Django 6.0 on 2026-01-06 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="time",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время окончания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время начала"
            ),
            preserve_default=False,
        ),
    ]
